config/routes.rb
Rails.application.routes.draw do
  root "articles#index"

  resources :articles do
    resources :comments
  end

  #resources :brackets

  # config/routes.rb
  post '/test_render_bracket', to: 'brackets#test_render_bracket'

  # config/routes.rb
  resources :brackets do
    get 'get_bracket_with_players', on: :member # Replace :your_controller with your actual controller name
  end

end

app/models/bracket.rb
# app/models/bracket.rb

class Bracket < ApplicationRecord
    #include Visible
  
    has_many :players, dependent: :destroy
  
    validates :players, presence: true
    end
  

app/controllers/brackets_controller.rb
class BracketsController < ApplicationController
  def new
    @bracket = Bracket.new
  end
  def create
    bracket_params = params.require(:bracket).permit(players: [:name])
    @bracket = Bracket.new
  
    # Generate a Double Elimination bracket template for 12 players
    num_players = 8
    template = BracketTree::Template::SingleElimination.by_size(num_players)
  
    # Seed the bracket with player data
    players_data = bracket_params[:players].values
  
    players = []
    @bracket = BracketTree::Bracket::SingleElimination.new(
      matches: template.matches,
      seed_order: template.seed_order
    )
   

    # Create players and associate them with seats
    @bracket.seats.each_with_index do |seat, index|
      if players_data[index].present?
        player = Player.create(name: players_data[index][:name])
        seat.player = player
        players << player
      end
    end
    # puts "Inspecting @bracket contents:"
    # puts @bracket.inspect


      # Serialize the bracket data to JSON
    bracket_data = @bracket.to_h # Assuming to_h method is implemented in Bracket class

    # Respond with JSON
    puts "Inspecting bracket_data contents:"
    puts bracket_data.inspect
    render json: { bracket_data: bracket_data }
    # Serialize the bracket data to JSON
    #bracket_data = @bracket.to_json
   
    #render json: { bracket_data: bracket_data }
   
    end
  end
  

  def show
    @bracket = Bracket.find(params[:id])
    @players = @bracket.seats.map(&:player)
  
    respond_to do |format|
      format.html # Render the HTML template (default behavior)
      format.json { render json: bracket_with_players_json }
      serializer = BracketSerializer.new(@bracket)
      render json: serializer.to_json
    end
   # @bracket = Bracket.find(params[:id])
    
  end
  
  private
  
  def bracket_with_players_json
    {
      matches: @bracket.matches.as_json(include: { seats: {} }),
      seats: @bracket.seats.as_json,
      starting_seats: @bracket.starting_seats,
      players: @players.as_json
    }

    def get_bracket_with_players
      @bracket = # Call your bracket_with_players_json method here
  
      respond_to do |format|
        format.json { render json: @bracket }
      end
  end
  
end

app/views/brackets/_bracket_tree.html.erb
<% output = '' %>
<% @bracket.rounds.each do |round| %>
  <% round.matches.each do |match| %>
    <% output += '<div class="match">' %>
    <% output += "<span>#{match.participant1.name}</span>" %>
    <% output += '<span>vs</span>' %>
    <% output += "<span>#{match.participant2.name}</span>" %>
    <% output += '</div>' %>
  <% end %>
<% end %>
<%= output.html_safe %>

app/views/brackets/_form.html.erb
<%= form_with model: @bracket, url: brackets_path, method: :post do |form| %>
  <!-- Form fields for bracket data here -->

  <% 8.times do |i| %>
    <div class="field">
      <%= form.label "players[#{i}][name]", "Player #{i + 1} Name" %>
      <%= form.text_field "players[#{i}][name]" %>
    </div>
  <% end %>

  <!-- Add more bracket fields as needed -->

  <div class="actions">
    <%= form.submit "Create Bracket" %>
  </div>
<% end %>

app/views/brackets/edit.html.erb
<h1>Edit Bracket</h1>

<%= render "form", bracket: @bracket %>

app/views/brackets/new.html.erb
<h1>New Bracket</h1>

<% if @bracket.new_record? %>
  <%= render "form", bracket: @bracket %>
<% end %>

app/views/brackets/new_html_bracket.erb
<h1>New Bracket</h1>


<%= render "form", bracket: @bracket %>

app/views/brackets/show.html.erb
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="/assets/application.js"></script> <!-- Include your custom JavaScript file -->

<% output = '' %>
<% @bracket.rounds.times do |round| %>
  <% round.matches.each do |match| %>
    <% output += '<div class="match">' %>
    <% output += "<span>#{match.participant1.name}</span>" %>
    <% output += '<span>vs</span>' %>
    <% output += "<span>#{match.participant2.name}</span>" %>
    <% output += '</div>' %>
  <% end %>
<% end %>
<%= output.html_safe %>